ftw/slider/browser/resources/slider.css
ftw/slider/browser/slider.pt

Added new title class for applying header styles.

Changed invalid HTML structure. 

---

docs/HISTORY.txt
ftw/slider/browser/configure.zcml
ftw/slider/tests/test_slider_creation.py

Change registration of custom slider container add view.
Also refactor tests to use ftw.testbrowser.

Add Plone 4.3.5 support.

---

docs/HISTORY.txt
ftw/slider/browser/resources/slider.js

Fixes 4teamwork/bern.web#149
Depends on 4teamwork/ftw.sliderblock#3, OneGov/plonetheme.onegovbear#6
Further changes should be done here for styling issues 4teamwork/bern.web#175
Implement play and pause button.
Use DOM exposed configuration for slider initialisation.
Extend configuration for play and pause functionality.

Rotating banner

---

docs/HISTORY.txt
ftw/slider/browser/resources/slider.js

Due to 4teamwork/bern.web#204 the slider
cannot get initialized twice. So an update function is required to not
adding the play and pause buttons twice.

Implement update function

---

docs/HISTORY.txt
ftw/slider/contents/pane.py

This allows us to us `@@imaging` without knowing the fieldname.

Mark image field as primary field.

---

docs/HISTORY.txt
ftw/slider/browser/resources/slider.js
ftw/slider/browser/slider.pt
ftw/slider/browser/slider.py
ftw/slider/contents/container.py
ftw/slider/tests/test_slickconfig.py
ftw/slider/tests/test_slider_appearance.py

@maethu 
- Add slick_config field to container schema
- Add css class if pane has text
- Initialize sliderpanes on pageload

Es 10744 slider

---

ftw/slider/browser/resources/slider.js

Fixes https://github.com/4teamwork/bern.web/issues/468
Depends on https://github.com/4teamwork/bern.web/pull/478
Use breakpoint event from slick js to determine if a breakpoint is
reached.

Custom responsive config e.g. ```canPlay``` is not considered.

---

ftw/slider/browser/resources/ftwtheming.scss
ftw/slider/browser/resources/slider.js

Fixes https://github.com/4teamwork/bern.web/issues/708

Review adjustments according to mediaparx.

---

docs/HISTORY.txt
ftw/slider/browser/slider.pt
ftw/slider/configure.zcml
ftw/slider/contents/pane.py
ftw/slider/profiles/default/metadata.xml
ftw/slider/profiles/default/types/ftw.slider.Pane.xml
ftw/slider/upgrades/20151029134948_remove_i_basic_behavior_from_pane/types/ftw.slider.Pane.xml
ftw/slider/upgrades/20151029134948_remove_i_basic_behavior_from_pane/upgrade.py

- Update sliderpane for 
- Show always empty image alt and title attributes on a pane
- Remove unused descriptionfield on a pane

Update sliderpane for accessiblity

---

docs/HISTORY.txt
ftw/slider/viewlets/configure.zcml

Prevent rendering the viewlet on non-canonical views.

Register ftw.slider.slider viewlet on IViewView.

---

docs/HISTORY.txt
ftw/slider/browser/resources/ftwtheming.scss
ftw/slider/browser/resources/slider.css
ftw/slider/browser/resources/slider.js

Fix slider pane initialization.

---

docs/HISTORY.txt
ftw/slider/browser/resources/ftwtheming.scss
ftw/slider/browser/resources/slider.css
ftw/slider/browser/resources/slider.js
ftw/slider/browser/slider.pt
ftw/slider/browser/slider.py

Fixes https://github.com/4teamwork/ftw.slider/issues/54

Update SCSS to the current ftw.theming version.

---

docs/HISTORY.txt
ftw/slider/browser/pane.pt
ftw/slider/browser/slider.pt
ftw/slider/contents/pane.py
ftw/slider/locales/de/LC_MESSAGES/ftw.slider.po
ftw/slider/locales/ftw.slider.pot
ftw/slider/tests/test_slider_pane.py
ftw/slider/upgrades/20161202110016_set_show_title_on_existing_slider_panes/upgrade.py

Until now the title was only rendered when the pane had some text.

Add option to render the title independently of the text

---

docs/HISTORY.txt
ftw/slider/contents/pane.py
ftw/slider/locales/de/LC_MESSAGES/ftw.slider.po
ftw/slider/locales/ftw.slider.pot

The message string was in the wrong domain.

Fix field label translation.

---

docs/HISTORY.txt
ftw/slider/browser/resources/ftwtheming.scss
ftw/slider/browser/slider.pt

Fix rendering of external link

---

docs/HISTORY.txt
ftw/slider/browser/resources/onegovtheme.sass
setup.py

 Fix overlapping text of slider.

---

README.rst

Add settings description for the json formatted textarea settings

---

README.rst
docs/HISTORY.txt
setup.py

Add classifier for Plone 5.1.

---

docs/HISTORY.txt
ftw/slider/browser/resources/slick.css

See https://github.com/kenwheeler/slick/issues/1367 for more information about the issue.

Fix pixel rounding issues on slick slider.

---

docs/HISTORY.txt
ftw/slider/profiles/default/types/ftw.slider.Container.xml
ftw/slider/profiles/default/types/ftw.slider.Pane.xml
ftw/slider/upgrades/20191113151347_set_effective_and_expiry_date_on_slider_container_and_panes/types/ftw.slider.Container.xml
ftw/slider/upgrades/20191113151347_set_effective_and_expiry_date_on_slider_container_and_panes/types/ftw.slider.Pane.xml
ftw/slider/upgrades/20191113151347_set_effective_and_expiry_date_on_slider_container_and_panes/upgrade.py

Fields are added via the `IPublication` behaviour from `plone.app.dexiterity`

Add effective and expiry date on slider container / pane

---

docs/HISTORY.txt
ftw/slider/locales/de/LC_MESSAGES/plone.po
ftw/slider/locales/plone.pot

part of https://github.com/4teamwork/izug.organisation/issues/1745

Add ftw.slider portal_types translations to plone domain.

---

docs/HISTORY.txt
ftw/slider/tests/__init__.py
ftw/slider/tests/test_slickconfig.py
ftw/slider/tests/test_slider_appearance.py
ftw/slider/tests/test_slider_creation.py
ftw/slider/tests/test_sliderpane_view.py
setup.py

Unittest2 is deprecated and therefore should be removed.

Remove unittest2.
