4teamwork/ftw.slider

docs/HISTORY.txt, ftw/slider/browser/resources/slider.css
We suppose this has initially been implemented so the arrows could be display when hovering the mouse over the image (in a custom plonetheme). Please update your theme if it depends on this behaviour.
=> Do not hide the slick arrows by default.

docs/HISTORY.txt, ftw/slider/browser/resources/slider.js
Fixes https://github.com/4teamwork/bern.web/issues/194
Due to
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset#Browser_compatibility
ie 10 does not support the dataset API. So use jQuery's data method for
accesssing the settings data attribute.
=> Slider throws error on initialize in ie10.

ftw/slider/profiles/default/types/ftw.slider.Container.xml, ftw/slider/profiles/default/types/ftw.slider.Pane.xml
The IReferenceable behavior adds the objects to the reference catalog.
We need this in order to lookup objects by UUID.
=> Enable IReferenceable on all types.

docs/HISTORY.txt, ftw/slider/browser/slider.pt
Be aware that scales caching requires plone.namedfile >= 2.0.8 and UID
based urls. plone.app.caching must be configured accordingly.
=> Use UID-based scaling urls in order to have caching.

docs/HISTORY.txt, ftw/slider/browser/resources/slider.js, ftw/slider/browser/slider.py, ftw/slider/locales/de/LC_MESSAGES/ftw.slider.po, ftw/slider/locales/ftw.slider.pot, ftw/slider/tests/test_slickconfig.py
Fixes https://github.com/4teamwork/bern.web/issues/611
Depends no https://github.com/4teamwork/ftw.sliderblock/pull/19
Extend slider with ```labels``` config for defining labels in action
button such as next, previous, play or pause.
=> Slider action buttons have only default labels.

docs/HISTORY.txt, ftw/slider/browser/listingblock_slider.py
According to https://github.com/4teamwork/ftw.slider/commit/3baed8689f3bf7e7be32778849962491780f1d22
the new syntax for slider initialisation uses `new Slider()` instead of `$().slick()`.
=> Update slider initialisation in listing block.

docs/HISTORY.txt, ftw/slider/browser/listingblock_slider.pt, ftw/slider/browser/listingblock_slider.py
https://extranet.4teamwork.ch/support/0314-support-www.bgbern.ch-burgergemeinde-bern/0314-tracker-neugestaltung-website-burgergemeinde-bern/280
=> Use image cropping for sliderblock images to keep from breaking the layout with different image ratios.

ftw/slider/browser/resources/slider.css
Closes https://extranet.4teamwork.ch/support/0314-support-www.bgbern.ch-burgergemeinde-bern/0314-tracker-neugestaltung-website-burgergemeinde-bern/282
During rewrite for ftw.theming here: https://github.com/4teamwork/ftw.slider/pull/55.
The diashow icon for the simplelayout action has been accidentally removed.
=> Fix icon for simplelayout diashow action.

docs/HISTORY.txt, ftw/slider/profiles/default/rolemap.xml, ftw/slider/upgrades/20160524145152_make_slider_panes_addable_on_site_root_for_site_manager/rolemap.xml, ftw/slider/upgrades/20160524145152_make_slider_panes_addable_on_site_root_for_site_manager/upgrade.py
The Site Administrator should be able to add slider panes in a slider on the site root (when the slider has no workflow).
=> let Site Administrator add panes on site root.

ftw/slider/browser/listingblock_slider.pt, ftw/slider/browser/listingblock_slider.py, ftw/slider/testing.py, ftw/slider/tests/__init__.py, ftw/slider/tests/builders.py, ftw/slider/tests/test_listingblock.py, setup.py
This error occurs in the slider view of a listing block containing files having umlauts in their file name.
I have not added an entry in the changelog because the bug has not yet been released.
The bug has been introduced in https://github.com/4teamwork/ftw.slider/pull/57
=> Fix UnicodeDecodeError.

docs/HISTORY.txt, ftw/slider/browser/resources/onegovtheme.sass
The slider changed his HTML structure so we have to update
the styling as well for the onegovtheme support.
=> Fix styling for onegovtheme since slider update.

docs/HISTORY.txt, ftw/slider/browser/configure.zcml, ftw/slider/browser/pane.pt, ftw/slider/browser/pane.py, ftw/slider/profiles/default/types/ftw.slider.Pane.xml, ftw/slider/tests/builders.py, ftw/slider/tests/test_sliderpane_view.py, ftw/slider/upgrades/20160721104124_add_new_pane_view/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20160721104124_add_new_pane_view/upgrade.py, test-plone-4.3.x.cfg
This is used for users, which accidentally hit (Search / direct input) the pane itself.
=> Add browser pane redirect view, which behaves like the one from links.

docs/HISTORY.txt, ftw/slider/browser/resources/ftwtheming.scss
The button in the screenshot would have a border-radius instead.
=> Use preconfigured border radius from ftw.theming instead of user-agent style

docs/HISTORY.txt, ftw/slider/browser/resources/onegovtheme.sass
The `site-platform` selector is too specific. This selector exactly addresses
a plone site named `platfrom`.
=> Fix spacing of slider folder

docs/HISTORY.txt, ftw/slider/testing.py, setup.py
This removes the dependency on the `ftw.testing[splinter]` extra, which has been [dropped from 
`ftw.testing`](https://github.com/4teamwork/ftw.testing/commit/6eadb49bed08a0b40113d65abf8b302935cb1007).
=> Remove dependency on ftw.testing[splinter]

docs/HISTORY.txt, ftw/slider/browser/pane.py, ftw/slider/browser/slider.pt, ftw/slider/browser/slider.py, ftw/slider/browser/utils.py, ftw/slider/tests/test_sliderpane_view.py
The internal links of the panes in the slider view must be of the form "http://hostname/path/to/target-folder" and not only "/target-folder" in order for the links to work on localhost too.
=> Improve internal link of panes in the slider view

docs/HISTORY.txt, ftw/slider/upgrades/20151029134948_remove_i_basic_behavior_from_pane/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20170824081802_add_i_name_from_title_behavior_to_ftw_slider_pane/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20170824081802_add_i_name_from_title_behavior_to_ftw_slider_pane/upgrade.py
The upgrade step introduced in https://github.com/4teamwork/ftw.slider/pull/49 seems to purge the existing behaviors.
=> Fix faulty upgrade step introduced in 2.3.1.

docs/HISTORY.txt, setup.py
This reverts commit a0d55b32cc4498e8e8a94ff153993748d22565e7.
ftw.slider does not implement splinter tests. (see #75 )
=> Revert "Splinter has been removed since for versions greater than 1.11.0"

README.rst, docs/HISTORY.txt, ftw/slider/browser/resources/slider.js
Add "random" config parameter to display the slides in a random sort-order on each reload
Order:
Random:
Configuration:
Closes #89 
Issuer: https://extranet.4teamwork.ch/extern/0202-projekt-edubs-ict-basler-schulen/tracker-edubs/1110
=> Add "random" config parameter to display the slides in a random sort-order

docs/HISTORY.txt, ftw/slider/contents/container.py, ftw/slider/profiles/default_plone5/types/ftw.slider.Container.xml, ftw/slider/profiles/default_plone5/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20200527190657_remove_plone_app_referenceablebehavior/types/ftw.slider.Container.xml, ftw/slider/upgrades/20200527190657_remove_plone_app_referenceablebehavior/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20200527190657_remove_plone_app_referenceablebehavior/upgrade.py
The first commits remove plone.app.referenceablebehavior in plone 5.
The last commit makes use of the interfaced referenced to in the type so that it is provided by the sliders container.
=> Remove referenceablebehavior in plone 5 and make use of interface.

docs/HISTORY.txt, ftw/slider/profiles/default_plone5/types/ftw.slider.Container.xml, ftw/slider/profiles/default_plone5/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20200923144814_remove_obsolete_behaviours/types/ftw.slider.Container.xml, ftw/slider/upgrades/20200923144814_remove_obsolete_behaviours/types/ftw.slider.Pane.xml, ftw/slider/upgrades/20200923144814_remove_obsolete_behaviours/upgrade.py
This behaviour is for Plone 4 only. For Plone 5, one can use plone.app.multilingual directly.
=> Remove obsolete behaviours in Plone 5
